baseURL = "https://526avijitgupta.github.io"
defaultContentLanguage = "en"
languageCode = "en"
title = "Avijit Gupta"
theme = "gokarna"
enableRobotsTXT = true

pygmentsStyle = "monokai"

[params]
  footer = "Avijit Gupta"
  description = "Travel · Capture · Code"
  avatarURL = "https://avatars0.githubusercontent.com/u/7583815?v=3&s=460"
  avatarSize = "size-m"
  customHeadHTML = ""
  showPostsOnHomePage = "popular"
  metaKeywords = ["blog", "gokarna", "hugo", "software", "avijit"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Resume"
    url = "https://github.com/526avijitgupta/526avijitgupta.github.io/raw/main/static/Avijit_Gupta.pdf"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/526avijitgupta"
    weight = 5

  [[menu.main]]
    identifier = "twitter"
    pre = "<span data-feather='twitter'></span>"
    url = "https://twitter.com/526avijit"
    weight = 6
